import { useMemo, useState } from 'react'
import { FiArrowLeft, FiBell, FiCalendar, FiCheckCircle, FiChevronRight, FiClock, FiDollarSign, FiFileText, FiHome, FiLock, FiPlus, FiSearch, FiShield, FiUsers } from 'react-icons/fi'
import { motion } from 'framer-motion'

const cases = [
  ['Budi Santoso', 'AJB', 'Proses PPAT', '10 menit lalu'],
  ['PT Sinar Abadi', 'Pendirian PT', 'Draft Akta', '32 menit lalu'],
  ['Siti Rahma', 'SKMHT', 'Menunggu tanda tangan', '1 jam lalu'],
  ['Andi Pratama', 'Balik Nama', 'Dokumen lengkap', '2 jam lalu'],
]

const nav = [['Dashboard', FiHome], ['Klien & Perkara', FiUsers], ['Akta & Dokumen', FiFileText], ['Pelacakan', FiClock], ['Agenda', FiCalendar], ['Invoice', FiDollarSign]]

const css = {
  page: { minHeight:'100vh', background:'#070b12', color:'#e9eef7', fontFamily:'Inter,system-ui,sans-serif', display:'flex' },
  side: { width:248, padding:20, boxSizing:'border-box', borderRight:'1px solid rgba(255,255,255,.08)', background:'#05080e', display:'flex', flexDirection:'column' },
  brand:{display:'flex',alignItems:'center',gap:10,fontSize:14}, logo:{width:34,height:34,borderRadius:9,display:'grid',placeItems:'center',background:'linear-gradient(135deg,#00f0ff,#7b2ff7)',color:'#061018',fontWeight:900},
  tenant:{marginTop:24,padding:14,borderRadius:12,background:'rgba(255,255,255,.035)',border:'1px solid rgba(255,255,255,.07)'},
  nav:{border:0,background:'transparent',color:'#8f9aad',padding:'10px 11px',borderRadius:9,display:'flex',alignItems:'center',gap:10,textAlign:'left',cursor:'pointer',fontSize:13}, active:{color:'#eafcff',background:'rgba(0,240,255,.08)',boxShadow:'inset 2px 0 #00f0ff'},
  main:{flex:1,minWidth:0,padding:'28px clamp(20px,4vw,48px)',boxSizing:'border-box',maxWidth:1500,margin:'0 auto'}, header:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,marginBottom:26}, crumb:{color:'#586478',fontSize:9,letterSpacing:1.5,fontWeight:800}, title:{fontSize:26,margin:'6px 0 0'},
  search:{display:'flex',alignItems:'center',gap:8,padding:'9px 12px',width:220,border:'1px solid rgba(255,255,255,.09)',borderRadius:9,background:'rgba(255,255,255,.035)',color:'#687386'}, input:{width:'100%',border:0,outline:0,background:'transparent',color:'#e9eef7',fontSize:11}, circle:{width:36,height:36,borderRadius:9,border:'1px solid rgba(255,255,255,.08)',background:'rgba(255,255,255,.035)',color:'#8994a7',display:'grid',placeItems:'center'}, avatar:{width:34,height:34,borderRadius:'50%',background:'#1a2433',display:'grid',placeItems:'center',fontSize:10,fontWeight:800,color:'#00e8f5'},
  hero:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,padding:24,borderRadius:16,border:'1px solid rgba(0,240,255,.13)',background:'linear-gradient(110deg,rgba(0,240,255,.07),rgba(123,47,247,.05))',marginBottom:18}, eyebrow:{color:'#00d9e8',fontSize:9,letterSpacing:1.4,fontWeight:800}, primary:{display:'inline-flex',alignItems:'center',gap:8,border:0,borderRadius:9,padding:'10px 15px',background:'linear-gradient(90deg,#00dce9,#7b2ff7)',color:'#fff',fontWeight:750,cursor:'pointer',fontSize:12},
  stats:{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:14,marginBottom:18}, stat:{display:'flex',gap:13,padding:18,borderRadius:13,border:'1px solid rgba(255,255,255,.07)',background:'rgba(255,255,255,.028)'}, icon:{width:38,height:38,borderRadius:10,display:'grid',placeItems:'center',background:'rgba(0,240,255,.08)',color:'#00e0ed',flexShrink:0}, muted:{color:'#7b8799',fontSize:10,textTransform:'uppercase',letterSpacing:.8}, value:{fontSize:20,fontWeight:750,marginTop:3}, note:{color:'#596678',fontSize:10,marginTop:3},
  grid:{display:'grid',gridTemplateColumns:'1.55fr 1fr',gap:18,marginBottom:18}, panel:{border:'1px solid rgba(255,255,255,.07)',borderRadius:14,background:'rgba(255,255,255,.025)',padding:19}, panelHead:{display:'flex',justifyContent:'space-between',gap:12,marginBottom:12}, panelTitle:{margin:0,fontSize:14}, sub:{margin:'4px 0 0',color:'#687487',fontSize:11}, row:{display:'flex',alignItems:'center',gap:11,padding:'13px 0',borderTop:'1px solid rgba(255,255,255,.055)'}, initials:{width:31,height:31,borderRadius:8,display:'grid',placeItems:'center',background:'#121a27',color:'#9ca8ba',fontSize:9,fontWeight:800}, status:{padding:'5px 8px',borderRadius:6,background:'rgba(0,240,255,.055)',color:'#74dce4',fontSize:9,whiteSpace:'nowrap'}, small:{color:'#778295',fontSize:11,marginTop:4},
  timeline:{display:'grid',gridTemplateColumns:'55px 1fr',gap:13,fontSize:11,color:'#aeb7c5'}, modalBg:{position:'fixed',inset:0,background:'rgba(0,0,0,.72)',display:'grid',placeItems:'center',zIndex:100}, modal:{width:'min(440px,calc(100vw - 32px))',background:'#0d131d',border:'1px solid rgba(0,240,255,.18)',borderRadius:16,padding:22,boxSizing:'border-box'}, field:{width:'100%',boxSizing:'border-box',padding:'11px 12px',borderRadius:8,border:'1px solid rgba(255,255,255,.09)',background:'#080d15',color:'#e8edf6',marginTop:7}, label:{display:'block',color:'#8f9aac',fontSize:10,letterSpacing:1,margin:'15px 0'},
}

function Stat({ icon:Icon, label, value, note }) { return <div style={css.stat}><div style={css.icon}><Icon size={18}/></div><div><div style={css.muted}>{label}</div><div style={css.value}>{value}</div><div style={css.note}>{note}</div></div></div> }

export default function NotaryDemo() {
  const [active,setActive]=useState('Dashboard'); const [q,setQ]=useState(''); const [modal,setModal]=useState(false)
  const filtered=useMemo(()=>cases.filter(c=>c.join(' ').toLowerCase().includes(q.toLowerCase())),[q])
  return <div style={css.page}>
    <aside style={css.side}>
      <div style={css.brand}><div style={css.logo}>S</div><div><b>Sistem Notaris</b><span style={{display:'block',fontSize:11,color:'#8490a3'}}>& PPAT</span></div></div>
      <div style={css.tenant}><div style={css.eyebrow}>DEMO KANTOR</div><b>Notaris & PPAT Maju</b><div style={css.small}>Tenant #DEMO-001</div></div>
      <nav style={{display:'grid',gap:6,marginTop:22}}>{nav.map(([label,Icon])=><button key={label} onClick={()=>setActive(label)} style={{...css.nav,...(active===label?css.active:{})}}><Icon size={17}/>{label}{active===label&&<FiChevronRight size={15} style={{marginLeft:'auto'}}/>}</button>)}</nav>
      <div style={{marginTop:'auto'}}><div style={{fontSize:10,color:'#758095',display:'flex',gap:6,alignItems:'center',marginBottom:12}}><FiShield/> Data tenant terisolasi</div><button onClick={()=>window.location.href='/'} style={{border:0,background:'transparent',color:'#8792a5',display:'flex',gap:8,alignItems:'center',cursor:'pointer',fontSize:11}}><FiArrowLeft/> Kembali ke portfolio</button></div>
    </aside>
    <main style={css.main}>
      <header style={css.header}><div><div style={css.crumb}>WORKSPACE / {active.toUpperCase()}</div><h1 style={css.title}>{active}</h1></div><div style={{display:'flex',gap:10,alignItems:'center'}}><div style={css.search}><FiSearch size={16}/><input aria-label="Cari" style={css.input} value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari klien, akta..."/></div><button style={css.circle}><FiBell/></button><div style={css.avatar}>IF</div></div></header>
      {active!=='Dashboard' ? <motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} style={{...css.panel,minHeight:430,display:'grid',placeItems:'center',textAlign:'center'}}><div><div style={{...css.icon,margin:'0 auto 18px'}}><FiFileText size={22}/></div><h2>{active}</h2><p style={{color:'#8b95a7',maxWidth:520,lineHeight:1.7}}>Preview modul. Demo ini memakai data simulasi dan tidak terhubung ke data klien nyata.</p><button style={css.primary} onClick={()=>setActive('Dashboard')}>Kembali ke Dashboard</button></div></motion.div> : <>
        <section style={css.hero}><div><div style={css.eyebrow}>MONDAY · 15 SEPTEMBER 2026</div><h2 style={{margin:'5px 0',fontSize:25}}>Selamat datang, Notaris.</h2><p style={{margin:0,color:'#a9b2c1'}}>Pantau pekerjaan kantor dalam satu workspace yang aman.</p></div><button style={css.primary} onClick={()=>setModal(true)}><FiPlus/> Perkara Baru</button></section>
        <section style={css.stats}><Stat icon={FiUsers} label="Klien aktif" value="128" note="+8 bulan ini"/><Stat icon={FiFileText} label="Akta berjalan" value="47" note="12 perlu perhatian"/><Stat icon={FiClock} label="Agenda hari ini" value="6" note="2 dalam 1 jam"/><Stat icon={FiDollarSign} label="Invoice outstanding" value="Rp 18,4 jt" note="14 invoice"/></section>
        <section style={css.grid}><div style={css.panel}><div style={css.panelHead}><div><h3 style={css.panelTitle}>Perkara terbaru</h3><p style={css.sub}>Aktivitas klien yang perlu dipantau</p></div></div>{filtered.map(c=><div key={c[0]} style={css.row}><div style={css.initials}>{c[0].split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div style={{flex:1}}><b>{c[0]}</b><div style={css.small}>{c[1]} · {c[3]}</div></div><span style={css.status}>{c[2]}</span><FiChevronRight color="#687386"/></div>)}</div>
        <div style={css.panel}><div style={css.panelHead}><div><h3 style={css.panelTitle}>Aktivitas</h3><p style={css.sub}>Jejak aktivitas terbaru</p></div></div>{[['Akta jual beli','Budi Santoso','Baru diperbarui'],['Invoice INV-2026-0912','PT Sinar Abadi','Pembayaran tercatat'],['Berkas balik nama','Andi Pratama','Dokumen lengkap']].map(x=><div key={x[0]} style={css.row}><FiCheckCircle color="#00dce9"/><div><b style={{fontSize:12}}>{x[0]}</b><div style={css.small}>{x[1]} · {x[2]}</div></div></div>)}</div></section>
        <section style={css.grid}><div style={css.panel}><div style={css.panelHead}><div><h3 style={css.panelTitle}>Agenda hari ini</h3><p style={css.sub}>Senin, 15 September</p></div></div><div style={css.timeline}><b>13:30</b><span>Penandatanganan AJB · Budi Santoso</span><b>15:00</b><span>Konsultasi PPAT · Siti Rahma</span><b>16:30</b><span>Review draft akta · PT Sinar Abadi</span></div></div><div style={{...css.panel,background:'linear-gradient(135deg,rgba(0,240,255,.09),rgba(123,47,247,.08))'}}><FiLock size={20}/><h3>Security by design</h3><p style={{color:'#9aa4b4',lineHeight:1.65}}>RBAC, tenant isolation, audit trail, secure session, CSRF protection dan kontrol akses dokumen.</p></div></section>
      </>}
    </main>
    {modal&&<div style={css.modalBg} onClick={()=>setModal(false)}><div style={css.modal} onClick={e=>e.stopPropagation()}><div style={css.panelHead}><div><h3 style={css.panelTitle}>Buat perkara baru</h3><p style={css.sub}>Demo UI — tidak menyimpan data.</p></div><button onClick={()=>setModal(false)} style={{border:0,background:'transparent',color:'#8b95a7',fontSize:24}}>×</button></div><label style={css.label}>NAMA KLIEN<input style={css.field} placeholder="Contoh: Budi Santoso"/></label><label style={css.label}>JENIS LAYANAN<select style={css.field}><option>Akta Jual Beli</option><option>Balik Nama</option><option>Pendirian PT</option><option>SKMHT</option></select></label><button style={{...css.primary,width:'100%',justifyContent:'center'}} onClick={()=>setModal(false)}>Simpan demo</button></div></div>}
  </div>
}
